name: "Sprocket Check"
author: "St. Jude Cloud Rust Labs"
description: "Check WDL documents for validity using Sprocket"
branding:
  icon: 'check-circle'
  color: 'blue'
inputs:
  # General options
  action:
    description: "Sprocket subcommand to run."
    required: true
    default: 'check'
  explicit-config-path:
    description: "Path to a TOML file to use for configuration. This TOML will be merged with any configuration file(s) found in the standard load order [https://sprocket.bio/configuration/overview.html#load-order]."
    required: false
  skip-config-search:
    description: "Enable the '--skip-config-search' Sprocket option, which disables the normal configuration search. Can be used with 'explicit-config-path' to load only the specified configuration file."
    required: false
    default: 'false'
  # Options for `check` and `lint` subcommands
  lint:
    description: "Whether to lint WDL documents."
    required: false
    default: 'false'
  exclude-patterns:
    description: 'Comma separated list of patterns to exclude from Sprocket check.'
    required: false
    default: ''
  deny-warnings:
    description: 'Fail the check if there are any warnings.'
    required: false
    default: 'false'
  deny-notes:
    description: 'Fail the check if there are any notes.'
    required: false
    default: 'false'
  except:
    description: 'Comma separated list of rules to exclude from Sprocket check.'
    required: false
    default: ''
  # Options for `validate` subcommand
  wdl_files:
    description: "Path to the WDL document for which to validate inputs."
    required: false
  inputs_files:
    description: "Path to the JSON file containing inputs to validate."
    required: false
outputs:
  status:
    description: "The status of the check"
runs:
  using: "docker"
  image: "Dockerfile"
  entrypoint: "/app/entrypoint.sh"
  env:
    INPUT_CONFIG: ${{ inputs.explicit-config-path }}
    INPUT_SKIP_CONFIG_SEARCH: ${{ inputs.skip-config-search }}
    INPUT_PATTERNS: ${{ inputs.exclude-patterns }}
    INPUT_WARNINGS: ${{ inputs.deny-warnings }}
    INPUT_NOTES: ${{ inputs.deny-notes }}
