name: "Sprocket"
author: "St. Jude Cloud Rust Labs"
description: "Use Sprocket in your GitHub Actions workflows"
branding:
  icon: 'check-circle'
  color: 'blue'
inputs:
  # General options
  action:
    description: "Sprocket subcommand to run."
    required: true
    default: 'check'
  sources:
    description: "Space separated list of one or more WDL documents/directories."
    required: false
    default: ''
  # Options for `check` and `lint` subcommands
  lint:
    description: "Whether to lint WDL documents."
    required: false
    default: 'false'
  exclude-patterns:
    description: 'Comma separated list of patterns to exclude from Sprocket check.'
    required: false
    default: ''
  deny-warnings:
    description: 'Fail the check if there are any warnings.'
    required: false
    default: 'false'
  deny-notes:
    description: 'Fail the check if there are any notes.'
    required: false
    default: 'false'
  except:
    description: 'Comma separated list of rules to exclude from Sprocket check.'
    required: false
    default: ''
  # Options for `validate` subcommand
  inputs_files:
    description: "Path to the JSON file containing inputs to validate."
    required: false
outputs:
  status:
    description: "The status of the subcommand"
runs:
  using: "docker"
  image: "Dockerfile"
  entrypoint: "/app/entrypoint.sh"
  env:
    # These are added explicitly because inputs with dashes in the name aren't
    # implicitly converted correctly to environment variables.
    INPUT_PATTERNS: ${{ inputs.exclude-patterns }}
    INPUT_WARNINGS: ${{ inputs.deny-warnings }}
    INPUT_NOTES: ${{ inputs.deny-notes }}
