name: "Sprocket Check"
author: "St. Jude Cloud Rust Labs"
description: "Check WDL documents for validity using Sprocket"
branding:
  icon: 'check-circle'
  color: 'blue'
inputs:
  lint:
    description: "Whether to lint the WDL document"
    required: false
    default: 'false'
  exclude-patterns:
    description: 'Comma separated list of patterns to exclude from Sprocket check.'
    required: false
    default: ''
  deny-warnings:
    description: 'Fail the check if there are any warnings.'
    required: false
    default: 'false'
  deny-notes:
    description: 'Fail the check if there are any notes.'
    required: false
    default: 'false'
  except:
    description: 'Comma separated list of rules to exclude from Sprocket check.'
    required: false
    default: ''
outputs:
  status:
    description: "The status of the check"
runs:
  using: "docker"
  image: "Dockerfile"
  entrypoint: "/app/entrypoint.sh"
  env:
    INPUT_PATTERNS: ${{ inputs.exclude-patterns }}
    INPUT_WARNINGS: ${{ inputs.deny-warnings }}
    INPUT_NOTES: ${{ inputs.deny-notes }}
