name: Test `check` and `lint` actions

on:
  push:
    branches:
      - main
      - run
  pull_request:

jobs:
  test-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        env:
          LOG_LEVEL: DEBUG
          GITHUB_WORKSPACE: test/check-lint
        with:
          action: check
          sources: test/check-lint/example.wdl test/check-lint foobar
  test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        env:
          LOG_LEVEL: DEBUG
          GITHUB_WORKSPACE: test/check-lint
        with:
          action: check
          sources: test/check-lint/example.wdl test/check-lint foobar